on: [push]

jobs:
  obs_helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: IRNYH8W4RQ3UEH91RF4I
          secret_access_key: tfbgYv43z6D5mBaQfjm2XfePdFEo1zU4mYXY8RDX
          region: 'cn-north-4'
        
      - name: Upload Folder to OBS
        uses: huaweicloud/obs-helper@v1.3.0
        with:
          bucket_name: 'dxh'
          local_file_path: ./resource/upload/folder2
          obs_file_path: src/upload/newFolder
          operation_type: upload
          include_self_folder: true